# auth service
service:
  name: auth-application
  image: kpring/auth-application
  tag: 4f73c170
  port: 8080
  nodePort: 30001
  jwt:
    duration:
      access: "3600000"
      refresh: "86400000"
redis:
  name: redis
  image: redis:alpine
  port: 6379
