# auth service
service:
  name: auth-application
  image: youdong98/kpring-auth-application:latest
  port: 8080
  nodePort: 30001
  jwt:
    duration:
      access: "3600000"
      refresh: "86400000"

redis:
  name: redis
  image: redis:alpine
  port: 6379
