# kubernetes on local environment
services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      URLS: "[{name: 'auth', url: 'http://152.70.145.249/auth/static/openapi3.yaml'},{name: 'user', url: 'http://152.70.145.249/user/static/openapi3.yaml'}, {name: 'server', url: 'http://152.70.145.249/server/static/openapi3.yaml'}]"
