# server service
service:
  name: server-application
  image: kpring/server-application
  tag: 4b648b78
  port: 8080
  nodePort: 30003
api:
  authServiceUrl: http://auth-application
mongo:
  name: server-mongo
  image: mongo:latest
  port: 27017
  username: local-user
  password: local@password1234
  database: mongodb
