ingress:
  name: kpring-ingress
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: kpring.duckdns.org
      paths:
        - path: /auth(/|$)(.*)
          pathType: ImplementationSpecific
          service: auth-application
        - path: /user(/|$)(.*)
          pathType: ImplementationSpecific
          service: user-application
        - path: /server(/|$)(.*)
          pathType: ImplementationSpecific
          service: server-application
  tls: []

default:
  name: default-ingress
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: kpring.duckdns.org
      paths:
        - path: /
          pathType: Prefix
          service: kpring-front-application
  tls: []


resources: {}
