{{- if .Values.global.enable.server }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  namespace: {{ .Release.namespace }}
spec:
  type: ClusterIP

  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
      protocol: TCP
  selector:
    app: {{ .Values.mongo.name }}
{{- end }}
